<?php
$z[0]=Array("field","",108,136);
$z[0][4]=array();
$z[0][4]['name']="typeurl";
$z[1]=Array("field","",138,167);
$z[1][4]=array();
$z[1][4]['name']="typename";
$z[2]=Array("channel","\r\n              <li><a href=\"[field:typeurl/]\"><i class=\"fa fa-caret-right\"></i> &nbsp;[field:typename/]</a></li>\r\n              ",295,477);
$z[2][4]=array();
$z[2][4]['type']="son";
$z[2][4]['noself']="yes";

?>