<?php
$z[0]=Array("field","",197,225);
$z[0][4]=array();
$z[0][4]['name']="typeurl";
$z[1]=Array("field","",227,256);
$z[1][4]=array();
$z[1][4]['name']="typename";
$z[2]=Array("arclist","\r\n          <div class=\"item\"> <a href=\"[field:arcurl/]\" class=\"thumb-link\"><img src=\"[field:picname/]\" alt=\"[field:title/]\"/></a>\r\n            <h4 class=\"title\"><a href=\"[field:arcurl/]\" title=\"[field:title/]\">[field:title/]</a></h4>\r\n            <div class=\"meta\"> <span><i class=\"fa fa-calendar\"></i> [field:pubdate function=\"MyDate('Y-m-d',@me)\"/]</span> <span> / by [field:writer/]</span> </div>\r\n            <p class=\"desc\">[field:description function=\"cn_substr(@me,160)\"/]...</p>\r\n          </div>\r\n          ",409,995);
$z[2][4]=array();
$z[2][4]['row']="5";
$z[2][4]['titlelen']="50";
$z[2][4]['orderby']="pubdate";

?>