<div class="item"> <a href="[field:arcurl/]" class="thumb-link"><img src="[field:picname/]" alt="[field:title/]"/></a>
            <h4 class="title"><a href="[field:arcurl/]" title="[field:title/]">[field:title/]</a></h4>
            <div class="meta"> <span><i class="fa fa-calendar"></i> [field:pubdate function="MyDate('Y-m-d',@me)"/]</span> <span> / by [field:writer/]</span> </div>
            <p class="desc">[field:description function="cn_substr(@me,160)"/]...</p>
          </div>