<div class="col-md-3 col-sm-6 col-xs-6 iw4-item">
          <div class="team-wrap text-center">
            <div class="team-img"> <a href="[field:arcurl/]"><img class="img-responsive" src="[field:picname/]" alt="[field:title/]"/></a>
              <div class="team-social"><a href="[field:arcurl/]"><i class="fa fa-eye"></i></a></div>
            </div>
            <div class="team-content">
              <h4><a href="[field:arcurl/]">[field:title/]</a></h4>
              <span class="designation">[field:typename/]</span>
              <p class="desc">[field:description function="cn_substr(@me,120)"/]...</p>
            </div>
          </div>
        </div>