{dede:pagestyle maxwidth='800' pagepicnum='12' ddmaxwidth='200' row='3' col='4' value='2'/}
{dede:img ddimg='/uploads/allimg/180403/1-1P403113J1.jpg' text='' width='960' height='720'} /uploads/allimg/180403/1-1P403113J1.jpg {/dede:img}
{dede:img ddimg='/uploads/allimg/180403/1-1P403113J2.jpg' text='' width='960' height='720'} /uploads/allimg/180403/1-1P403113J2.jpg {/dede:img}
{dede:img ddimg='/uploads/allimg/180403/1-1P403113J3.jpg' text='' width='960' height='720'} /uploads/allimg/180403/1-1P403113J3.jpg {/dede:img}
