{dede:pagestyle maxwidth='800' pagepicnum='12' ddmaxwidth='200' row='3' col='4' value='2'/}
{dede:img ddimg='/uploads/allimg/180403/1-1P403114117.jpg' text='' width='960' height='720'} /uploads/allimg/180403/1-1P403114117.jpg {/dede:img}
{dede:img ddimg='/uploads/allimg/180403/1-1P403114118.jpg' text='' width='960' height='720'} /uploads/allimg/180403/1-1P403114118.jpg {/dede:img}
{dede:img ddimg='/uploads/allimg/180403/1-1P403114119.jpg' text='' width='960' height='720'} /uploads/allimg/180403/1-1P403114119.jpg {/dede:img}
