<?php
$z[0]=Array("global","",220,245);
$z[0][4]=array();
$z[0][4]['name']="cfg_cmsurl";
$z[1]=Array("global","",671,693);
$z[1][4]=array();
$z[1][4]['name']="cfg_tel";
$z[2]=Array("global","",707,729);
$z[2][4]=array();
$z[2][4]['name']="cfg_adr";
$z[3]=Array("global","",753,777);
$z[3][4]=array();
$z[3][4]['name']="cfg_phone";
$z[4]=Array("global","",800,824);
$z[4][4]=array();
$z[4][4]['name']="cfg_email";
$z[5]=Array("arclist","\r\n          <li>\r\n            <figure><a href=\"[field:arcurl/]\"><img src=\"[field:picname/]\"/></a></figure>\r\n            <div class=\"sn-wrapper\">\r\n              <p class=\"s-desc\"><a href=\"[field:arcurl/]\" title=\"[field:title/]\">[field:title/]</a></p>\r\n              <span class=\"comments\"><i class=\"fa fa-calendar\"></i> &nbsp;[field:pubdate function=\"MyDate('Y-m-d',@me)\"/]</span> </div>\r\n          </li>\r\n          ",1056,1552);
$z[5][4]=array();
$z[5][4]['typeid']="16";
$z[5][4]['row']="3";
$z[5][4]['titlelen']="50";
$z[5][4]['orderby']="pubdate";

?>